datasets:
  webvid_instruct:
    data_type: image
    build_info:
      anno_dir: /video_llama/datasets/videochat/videochat_instruct_11k.json
      videos_dir: video_llama/datasets/webvid-dataset/10M/train/
